SELECT * FROM NHOM_TAIKHOAN
SELECT * FROM TAIKHOAN

-- XÓA LIÊN KẾT TÀI KHOẢN VỚI NHÓM TÀI KHOẢN 
-- XÓA LIÊN KẾT TÀI KHOẢN VỚI CĂN HỘ
-- XÓA LIÊN KẾT TÀI KHOẢN VỚI NHÂN VIÊN_TÒA NHÀ

-- NỐI LIÊN KẾT NHÓM TÀI KHOẢN VÀO TÀI KHOẢN

-- THÊM NHÓM TÀI KHOẢN
INSERT NHOM_TAIKHOAN (MANHOM_TAIKHOAN,TENNHOM_TAIKHOAN)
VALUES ('ADMIN','ADMIN')
GO
INSERT NHOM_TAIKHOAN (MANHOM_TAIKHOAN,TENNHOM_TAIKHOAN)
VALUES ('RESIDENT','CƯ DÂN')
GO
INSERT NHOM_TAIKHOAN (MANHOM_TAIKHOAN,TENNHOM_TAIKHOAN)
VALUES ('STAFF','NHÂN VIÊN')
GO

-- THÊM TÀI KHOẢN
INSERT TAIKHOAN (TENDANGNHAP,MATKHAU,MANHOM_TAIKHOAN)
VALUES('ADMIN','123','ADMIN')
GO
INSERT TAIKHOAN (TENDANGNHAP,MATKHAU,MANHOM_TAIKHOAN)
VALUES('USER','123','STAFF')
GO
INSERT TAIKHOAN (TENDANGNHAP,MATKHAU,MANHOM_TAIKHOAN)
VALUES('TOI','123','RESIDENT')
GO


-- proc Login
CREATE PROCEDURE PR_login 
 @username varchar(30), @password varchar(30)
AS
BEGIN
	SELECT * FROM TAIKHOAN WHERE TENDANGNHAP = @username and MATKHAU = @password
END
GO

exec PR_login 'admin','123'
GO

-- proc cư dân

CREATE PROCEDURE PR_InserResident
 @MaCuDan varchar(30), @TenCuDan nvarchar(50),@NgaySinh date,@SoDienThoai varchar(10),@Cmnd varchar(10)
AS
BEGIN	
	INSERT CUDAN (MACUDAN,TENCUDAN,NGAYSINH,SODIENTHOAI,CHUNGMINHNHANDAN)
	VALUES (@MaCuDan,@TenCuDan,@NgaySinh,@SoDienThoai,@Cmnd) 
END
GO
	

CREATE PROCEDURE PR_InserResidentApartment
 @MaCuDan varchar(30), @MaCanHo varchar(30)
AS
BEGIN	
	INSERT [CUDAN-CANHO] (MACANHO,MACUDAN,NGAYBATDAUO,NGAYHETO)
	VALUES (@MaCanHo,@MaCuDan,GETDATE(),'2999-05-01') 
END
GO

CREATE PROCEDURE PR_UpdateResidentApartment
 @id int ,@MaCuDan varchar(30), @MaCanHo varchar(30), @ngayVaoO date, @ngayHetO date
AS
BEGIN	
	UPDATE [CUDAN-CANHO] 
	SET MACANHO = @MaCanHo,MACUDAN=@MaCuDan,NGAYBATDAUO =@ngayVaoO,NGAYHETO = @ngayHetO
	where ID = @id
END
GO